namespace MyGame.Enums;

public enum BlockType
{
    STONE_TOP_LEFTCORNER,
    STONE_TOP,
    STONE_TOP_RIGHTCORNER,
    STONE_LEFT,
    STONE_CENTER,
    STONE_RIGHT,
    STONE_BOTTOM_LEFTCORNER,
    STONE_BOTTOM,
    STONE_BOTTOM_RIGHTCORNER,
    EARTH_TOP,
    EARTH_CENTER,
}